// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "BestCS.Math.Optimization.ConjugateGradientMethod")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value", Scope = "member", Target = "BestCS.Math.Matrix.#Equals(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "IsEqual", Scope = "member", Target = "BestCS.Math.Matrix.#Equals(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "BestCS.Math.Optimization.IObjectiveFunction.#Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "m", Scope = "member", Target = "BestCS.Math.Special.#Log1m(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "p", Scope = "member", Target = "BestCS.Math.Special.#Log1p(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "evl", Scope = "member", Target = "BestCS.Math.Special.#P1evl(System.Double,System.Double[],System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "BestCS.Math.ComparerDirection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "BestCS.Math.Comparers.ComparerDirection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "BestCS.Math.Kinematics.DenavitHartenbergModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "BestCS.Math.Optimization.IGradientOptimizationMethod.#Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "BestCS.Math.Optimization.ILeastSquaresMethod.#Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ParameterTolerance", Scope = "member", Target = "BestCS.Math.Optimization.BroydenFletcherGoldfarbShanno.#Optimize()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "BestCS.Math.Integration.IUnivariateIntegration.#Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "BestCS.Math.Integration.IMultidimensionalIntegration.#Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "BestCS.Math.ISingleValueConvergence")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "BestCS.Math.RelativeParameterConvergence.#BestCS.Math.IConvergence`1<System.Double[]>.NewValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "BestCS.Math.RelativeParameterConvergence.#BestCS.Math.IConvergence`1<System.Double[]>.NewValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#DFT(BestCS.Math.Compatibility.ComplexWrapper[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#DFT2(BestCS.Math.Compatibility.ComplexWrapper[][],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT(BestCS.Math.Compatibility.ComplexWrapper[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT2(BestCS.Math.Compatibility.ComplexWrapper[][],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#DFT(System.Numerics.Complex[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#DFT2(System.Numerics.Complex[][],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT(System.Numerics.Complex[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT2(System.Numerics.Complex[][],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#DFT(BestCS.Math.Complex[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#DFT2(BestCS.Math.Complex[][],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT(BestCS.Math.Complex[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT(System.Double[],System.Double[],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "FFT", Scope = "member", Target = "BestCS.Math.Transforms.FourierTransform2.#FFT2(BestCS.Math.Complex[][],BestCS.Math.FourierTransform+Direction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "BestCS.IO.MatNode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "BestCS.IO.MatNode.#Value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Q", Scope = "member", Target = "BestCS.Math.Optimization.FanChenLinQuadraticOptimization.#.ctor(System.Int32,System.Func`3<System.Int32,System.Int32,System.Double>,System.Double[],System.Int32[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Q", Scope = "member", Target = "BestCS.Math.Optimization.FanChenLinQuadraticOptimization.#.ctor(System.Int32,System.Func`3<System.Int32,System.Int32,System.Double>)")]
